FROM alpine:3.4

RUN apk add --no-cache gcc g++ make cmake python3-dev \
                       boost-dev boost-python3 && \
    pip3 install --no-cache wheel

ENV PYTHON_VERSION=3.5

RUN mkdir /code /build
WORKDIR /build
CMD ["sh"]
