FROM ubuntu:16.04

RUN set -x \
    && apt-get update \
    && apt-get install -y gcc g++ cmake libicu-dev libbz2-dev libboost-dev \
               libboost-filesystem-dev libboost-regex-dev
RUN apt-get install -y python2.7-dev libboost-python-dev
ENV PYTHON_VERSION=2.7

RUN mkdir /code /build
WORKDIR /build
CMD ["bash"]
