FROM blitznote/debootstrap-amd64:17.04

RUN set -x \
    && apt-get update \
    && apt-get install -y \
               gcc g++ cmake libicu-dev libbz2-dev libboost-dev \
               libboost-filesystem-dev libboost-regex-dev libboost-python-dev
RUN apt-get install -y python3-dev python3-pip python3-setuptools

ENV PYTHON_VERSION=3.5

RUN mkdir /code /build
WORKDIR /build
CMD ["bash"]
